import Product from '../../shared/interfaces/Products'
import iso1005LB from '../../assets/most-popular-products/iso100-protein-5lb.png'
import ironNutririonCreatine from '../../assets/most-popular-products/iron-nutrition-creatine.png'
import muscletechCreatine from '../../assets/most-popular-products/muscletech-creatine.png'
import iso1001LB from '../../assets/most-popular-products/iso100-protein-1.3lb.png'

export const mockedProducts: Product[] = [
  {
    id: 1,
    stars: 4,
    title: 'Proteína Whey',
    description: '5LB',
    image: iso1005LB,
    originalPrice: '150.000$',
    discountedPrice: '120.000$',
    category: 'Proteínas',
    reviews: 10,
  },
  {
    id: 2,
    stars: 5,
    title: 'Creatina Monohidratada',
    description: '500g',
    image: ironNutririonCreatine,
    originalPrice: '80.000$',
    discountedPrice: '70.000$',
    category: 'Creatinas',
    reviews: 20,
  },
  {
    id: 3,
    stars: 3,
    title: 'Pre Entreno',
    description: '400g',
    image: muscletechCreatine,
    originalPrice: '100.000$',
    discountedPrice: '90.000$',
    category: 'Pre Entrenos',
    reviews: 5,
  },
  {
    id: 4,
    stars: 2,
    title: 'Proteína Iso 100',
    description: '1.3LB',
    image: iso1001LB,
    originalPrice: '210.000$',
    discountedPrice: '170.000$',
    category: 'Proteínas',
    reviews: 0,
  },
  {
    id: 5,
    stars: 4,
    title: 'Proteína Whey Gold Standard',
    description: '5LB',
    image:
      'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcReDgPDRdrE6-bRDbschMNuhQVuLH3x8vQ3eC5qA4hjuSeFeffXfNgaVEwHy-5_RxN0o9zkElMxiqjyqksmRZDtFJw02Iqt6fbuz7yJb1mCU_prfU2UHeYk0dC9LmPL9-RWTMy32wJ87n-X&usqp=CAc',
    originalPrice: '150.000$',
    discountedPrice: '120.000$',
    category: 'Proteínas',
    reviews: 10,
  },
  {
    id: 6,
    stars: 5,
    title: 'Creatina Monohidratada Micronizada',
    description: '500g',
    image:
      'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR-5jgwaVcyAcXIN31fpVrjoXsWdL59pcKO0qHw4viOhQcsHSktaXIhu4-maryPIn1h1woH-sAK6O1TaZ3-ZtG6NhGWutJXLIqCud4ji2HImhh-qJlynvzOoAUoTlFCTZgD0_myL-6s2A&usqp=CAc',
    originalPrice: '80.000$',
    discountedPrice: '70.000$',
    category: 'Creatinas',
    reviews: 20,
  },
  {
    id: 7,
    stars: 3,
    title: 'Pre Entreno C4 Original',
    description: '30 Servings',
    image:
      'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQfhgNEvXbM-k17HwPiHzGh29nynym6qaL_oZBDT4FYPoyt9gDHMi44wOBIoHN9OiE_1a03l2EMuj0uIdnjZiM7ZEkaV7sNW7UUp2YvN3F9y4KwoiBXcF8Sjr7b1nRH4pVmsNST410GA2s&usqp=CAc',
    originalPrice: '100.000$',
    discountedPrice: '90.000$',
    category: 'Pre Entrenos',
    reviews: 5,
  },
  {
    id: 8,
    stars: 2,
    title: 'Proteína Iso 100 Dymatize',
    description: '1.3LB',
    image:
      'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTweIK-MTiFwUTGlROiQRUYYIr1BGS7qig39XtXw6HY7N7v-VnF0dt5ktSpRAj49XnwHjq8Y-m2gXx_wNPaydm2WLPrLkOrHFh1qLyH8gvBePIMF0dGmO173VssPzfDkhmOs5Gwpw&usqp=CAc',
    originalPrice: '210.000$',
    discountedPrice: '170.000$',
    category: 'Proteínas',
    reviews: 0,
  },
  {
    id: 9,
    stars: 4,
    title: 'BCAA 5000 Powder',
    description: '345g',
    image:
      'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTT7GiqS_m4dZvjx4yQASNAo_98hjmkUHbDNNqGJGpLtdsNlc9viMx6WkRJL8TvhuDf7dQF5MYhewaOJEIIQP6Oh9QblQXPjQylfaZsNMiWP6Ls1gBEzl0N7gJ7s9J4ENfmWhwp5uw&usqp=CAc',
    originalPrice: '120.000$',
    discountedPrice: '100.000$',
    category: 'Aminoácidos',
    reviews: 15,
  },
  {
    id: 10,
    stars: 5,
    title: 'Glutamina Micronizada',
    description: '300g',
    image:
      'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQp3ZoiNPJbkzgKlpEBV4Nr1jCTAig9kl6fo2b_M9PHDRuppBmcGNIHnHqC0pQtl1TKLfaTa5Ix9u0NGQXuAB939GXCi-pXssCHmujMaI05XWncyWJaD2MCNI-fXlCWexxmgBkwsso&usqp=CAc',
    originalPrice: '90.000$',
    discountedPrice: '80.000$',
    category: 'Aminoácidos',
    reviews: 25,
  },
  {
    id: 11,
    stars: 3,
    title: 'Omega 3',
    description: '120 cápsulas',
    image:
      'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQYym0PWj10MrJoGyGRe9RvFEfgmRcPAJIHSp5H1jLcilWkdHsd9pcOe2SPHnPc_5PL9qAobTdmONNsQ2n45xQpjPtxudK9rq3mKirC5W5mIAZTKh8gpfeL4peT3sASujQjSIGyMrg&usqp=CAc',
    originalPrice: '70.000$',
    discountedPrice: '60.000$',
    category: 'Suplementos',
    reviews: 8,
  },
  {
    id: 12,
    stars: 4,
    title: 'Multivitamínico',
    description: '90 cápsulas',
    image:
      'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRKE6uCO0RCtaoA2PVcq_F8OP9KuDufUhnQSAeGdFYVwtDBUXfYJV5OoXKnS7_V8hWrD9pcEvwoz6xTS5ZLsEW6R2A6aMIkmCBLfvGnLiLEIWXfQhvc3cuQK3TbF1h_eglWBZzaSUJq&usqp=CAc',
    originalPrice: '50.000$',
    discountedPrice: '40.000$',
    category: 'Vitaminas',
    reviews: 12,
  },
  {
    id: 13,
    stars: 5,
    title: 'Barra Proteica',
    description: 'Caja x 12 unidades',
    image:
      'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQngoK2YB3Axpwy9cgv4MfVpTSpWPSDqqjaUvx3SKylda5n7iMhtSyNwZjWLeJRi2IGz8r2BIz9QYwfglUqGMJAxa3iKg2Ty0jLg1UgQpxpjPPXDRd5laXvzRnbEu77CGQoAidp-hbfHPc&usqp=CAc',
    originalPrice: '100.000$',
    discountedPrice: '85.000$',
    category: 'Snacks',
    reviews: 30,
  },
  {
    id: 14,
    stars: 4,
    title: 'Caseína Micelar',
    description: '2LB',
    image:
      'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQOk9RsFQPtq9uTkCPIIqloy2U7-OzsBKxMSaagMhIjDaW50HxE2SPfL9scCtQtvIora5t3Lzb1eJ_-5g8G8vg3SfTAa09DLMpGB5VMw9B7YPbjFBibxgZX',
    originalPrice: '130.000$',
    discountedPrice: '110.000$',
    category: 'Proteínas',
    reviews: 14,
  },
  {
    id: 15,
    stars: 3,
    title: 'ZMA',
    description: '90 cápsulas',
    image:
      'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQjn-HPfILOi5Uh4f6yIMXzMXUzqNhNJOx7iD9u0GbYFB1dy2HqONfBTF_eiHTRJ3YVK7sRmQ-zzz4oaiVa_kwIUS4PXU7Bq889lhjP9WllDlu5uhqL35G4NQ',
    originalPrice: '80.000$',
    discountedPrice: '70.000$',
    category: 'Minerales',
    reviews: 18,
  },
]
